### ISSUE TITLE
符號"-"在打字中沒有被錄入

### ISSUE THREAD

**Issue by zhaose233** [xrq-phys/rime-hifumi#2]
如想要打出 "アーチ" 這個詞，那麼應該在鍵盤上輸入 "a-chi"，但是"-"沒有被識別，看上去好像是被當作翻頁鍵處理了

**Comment by zhaose233** [comment]
```yaml
key_binder:
  bindings:
    - {accept: "Control+Shift+1", select: .next, when: always}
    - {accept: "Control+Shift+l", select: international, when: always}
    - {accept: "Control+Shift+L", select: international, when: always}
    - {accept: "F16", select: .next, when: always}
    - {accept: "F19", select: international, when: always}
```
參考了別一 rime 日文方案之後發現改寫 keybinder 可以解決此問題

**Comment by xrq-phys** [comment]
感谢反馈。

因为本人常年用 macOS 的方括号翻页配置没有注意到这个问题。~现在的配置下可以用 `q` 输入横线。~

**Comment by hykxygcxy** [comment]
具体输入引擎是小狼毫。尝试用了`q`， 无法输入`ー`。
使用如下方法改写keybinder
``` yaml
key_binder:
  bindings:
    - {accept: minus, send: minus, when: paging} #注销减号翻页
    - {accept: equal, send: equal, when: has_menu} 
    - {accept: bracketleft, send: Page_Up, when: paging} # [上翻页
    - {accept: bracketright, send: Page_Down, when: has_menu} # ]下翻页
```
但是现在仍然存在问题。每次需要输入`ー`时，都要按两次减号。

**Comment by xrq-phys** [comment]
您好。抱歉一个月没有回应。

这个 `-` 字符入 composer 是日语输入法的标准行为（MS-IME, Google-IME, Apple Japanese Input）所以 Rime-Hifumi 也这么设置了。然后抱歉之前写错了：
> ~现在的配置下可以用 q 输入横线。~

当前为了节省词典容量并没有设置 `q` 到 `-` 的转换。

所以您如果要设置 `q` 输入横线而让 `-` 直接上屏，可以考虑在 Rime 配置目录下创建 `hifumi.custom.yaml`：
```yaml
patch:
  "speller/alphabet": "abcdefghijklmnopqrstuvwxyz_"
  "speller/algebra":
    - 'derive/-/q/'
```

如此可以补全 `q` 到 `-` 的转换并且排除 `-` 使其不进入 composer 画面。
